name: Deploy [MAIN]

on:
  push:
    branches:
      - main

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Obtaining the code
        uses: actions/checkout@v1

      - name: Build and generate Maven files
        run: ./gradlew publish
