name: Deploy [MAIN]

on:
  push:
    branches:
      - main

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - name: Obtaining the code
        uses: actions/checkout@v1

      - name: Build
        run: ./gradlew build

      - name: Generate Maven files
        run: |
          ./gradlew publish -Dargs=$(git describe --tags)
          ls -l core/build/outputs/maven/dev/wearkit/core
