name: Deploy [MAIN]

on:
  push:
    branches:
      - main

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - name: Obtaining the code
        uses: actions/checkout@v1

      - name: Build & Test
        run: ./gradlew build

      - name: Generate Maven Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew publish -Dargs=$(git describe --tags)

      - name: Upload Artifacts
        env:
          MAVEN_REPO_RSA: ${{ secrets.MAVEN_REPO_RSA }}
        run: |
          mkdir -m 700 -p $HOME/.ssh
          echo "$MAVEN_REPO_RSA" > $HOME/.ssh/id_rsa
          chmod 400 $HOME/.ssh/id_rsa
          ssh-keyscan maven.tocappgames.com > $HOME/.ssh/known_hosts
          rsync -av core/build/outputs/maven/* wearkit@maven.tocappgames.com:maven.wearkit.dev