name: Deploy [MAIN]

on:
  push:
    branches:
      - main

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - name: Obtaining the code
        uses: actions/checkout@v1

      - name: Build & Test
        run: ./gradlew build

      - name: Publish Maven Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew publish -Dargs=$(git describe --tags)

      - name: Upload to maven.wearkit.dev
        run: |
          mkdir -m 700 -p $HOME/.ssh
          cat <<EOF > $HOME/.ssh/id_rsa
          ${{ secrets.MAVEN_REPO_RSA }}
          EOF
          chmod 400 $HOME/.ssh/id_rsa
          ssh-keyscan maven.wearkit.dev > $HOME/.ssh/known_hosts
          rsync -av core/build/outputs/maven wearkit@maven.wearkit.dev:maven.wearkit.dev