name: Deploy [MAIN]

on:
  push:
    branches:
      - main

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - name: Obtaining the code
        uses: actions/checkout@v1

      - name: Build & Test
        run: ./gradlew build

      - name: Publish Maven Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew publish -Dargs=$(git describe --tags)
